version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "9200:80"
    depends_on:
      - api
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: test
    depends_on:
      - mysql
    networks:
      - backend

  
volumes:
  mysql_data:

networks:
  backend:
