version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9306:9306"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: appdb
    depends_on:
      - mysql
    ports:
      - "9090:9090"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"

volumes:
  mysql-data: