version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "9200:80"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "9090:9090"
    environment:
      DB_HOST: mysql
      DB_PORT: 9306
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: test
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: test
    ports:
      - "9306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
